-- Weekly bitcoin editorial reports generated by a local worker.
CREATE TABLE IF NOT EXISTS weekly_reports (
  id BIGSERIAL PRIMARY KEY,
  slug TEXT NOT NULL,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  title TEXT NOT NULL,
  dek TEXT,
  summary TEXT NOT NULL,
  market_view TEXT NOT NULL,
  onchain_view TEXT NOT NULL,
  risk_watch TEXT NOT NULL,
  watchlist JSONB NOT NULL DEFAULT '[]'::JSONB,
  sections JSONB NOT NULL DEFAULT '[]'::JSONB,
  market_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
  onchain_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  model_name TEXT,
  generated_by TEXT NOT NULL DEFAULT 'local_codex_worker',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_weekly_reports_slug UNIQUE (slug),
  CONSTRAINT uq_weekly_reports_week_start UNIQUE (week_start)
);

CREATE INDEX IF NOT EXISTS idx_weekly_reports_week_start_desc
  ON weekly_reports (week_start DESC);

CREATE INDEX IF NOT EXISTS idx_weekly_reports_published_at_desc
  ON weekly_reports (published_at DESC);

ALTER TABLE weekly_reports ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS weekly_report_news_items (
  id BIGSERIAL PRIMARY KEY,
  report_slug TEXT NOT NULL REFERENCES weekly_reports(slug) ON DELETE CASCADE,
  rank INTEGER NOT NULL,
  title TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_url TEXT NOT NULL,
  published_at TIMESTAMPTZ,
  summary TEXT NOT NULL,
  why_it_matters TEXT NOT NULL,
  topic TEXT,
  priority INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_weekly_report_news_rank UNIQUE (report_slug, rank)
);

CREATE INDEX IF NOT EXISTS idx_weekly_report_news_report_slug_rank
  ON weekly_report_news_items (report_slug, rank ASC);

ALTER TABLE weekly_report_news_items ENABLE ROW LEVEL SECURITY;
